### ISSUE TITLE
Split facts on different character

### ISSUE THREAD

**Issue by vmcj** [KoenKahlman/aappgen#1]
the `=` is used by teams in the name so should have another way. If we do actual xlsx we could misuse the comments (if these do work in libreoffice and google docs etc.)

https://github.com/KoenKahlman/aappgen/blob/a4267b2b0b73253512ed8ae91c4bf09ba450b95d/aappgen.py#L21

**Comment by ChloeKahlman** [comment]
Splitting on '=' has been fixed. The format is always "PC-XXXXXX = \<name\>", so splitting on '=' once is already enough. Splitting on ';' will become obsolete once I read the floor layout from the .xlsx directly. I looked into how to do this and it seems pretty straightforward.

**Comment by ChloeKahlman** [comment]
resolved with latest version

**Comment by vmcj** [comment]
Just so you know, if you say something like:
"closes: #1" in the PR and the PR is merged it will autoclose the issue.
